apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: datavol
  name: datavol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
