apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  labels:
    {{- include "widgetapi.labels" . | nindent 4 }}
  name: datavol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
