apiVersion: v1
kind: Service
metadata:
  name: {{ include "widgetapi.fullname" . }}
  labels:
    {{- include "widgetapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "8080"
      port: {{ .Values.service.port }}
      targetPort: 8080

  selector:
    {{- include "widgetapi.selectorLabels" . | nindent 4 }}
