apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: widgetapi
  name: widgetapi
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: widgetapi
